### ISSUE TITLE
USB CDC Only

### ISSUE THREAD

**Issue by ForbiddenEra** [google/web-serial-polyfill#17]
Hi,

I hadn't seen this polyfill until recently although it's only going to work for USB CDC devices.

FTDI USB-to-Serial devices are quite popular and used in many devices (for example, most Arduinos, Raspberry Pi). The FTDI devices require a different approach when communicating with them. The proper way to do it is demonstrated in the Linux kernel driver source. I tried to get FTDI to send me some details but they got super squeamish when I mentioned open source even though the Linux driver is.

I then wrote my own driver, it's not ready yet but it's a good start, I'd be open to it being used here to make the polyfill more compatible.

Thanks.

**Comment by reillyeon** [comment]
Your contribution to this project is welcome. Let's track this on #8.
