### ISSUE TITLE
NPM package outdated

### ISSUE THREAD

**Issue by stylesuxx** [google/web-serial-polyfill#18]
Could you please publish a new package to NPM, the current one is two years old.

**Comment by reillyeon** [comment]
@jameshollyergoogle, can you push a new NPM packages with the recent API shape changes?

**Comment by JamesHollyer** [comment]
Done. Thanks for the ping on that @stylesuxx.

**Comment by stylesuxx** [comment]
Awesome, thanks for the quick response.
