### ISSUE TITLE
web-serial-polyfill and web-serial desktop and Android

### ISSUE THREAD

**Issue by hpssjellis** [google/web-serial-polyfill#40]
@reillyeon 

So I am doing better with web-serial-polyfill getting better speeds on Android, my forked github is [here](https://github.com/hpssjellis/web-serial-polyfill) and demo page is [here](https://hpssjellis.github.io/web-serial-polyfill/index.html)

What I would like to do is make equivalent pages for both polyfill and webUSB, but I can't find a simple webUSB github or code example except for this working demo [here](https://googlechromelabs.github.io/serial-terminal/) which I strangely can't even find the github for it.

I am having some minor issues with polyfill getting the reader and writer objects properties and methods printed and switching from promises to async/await. Other than that things are going well

For both situations my simple working Arduino code is

```

/*
 * webSerial for testing javascript connection with an arduino
 * 
 * Note: On the Arduino Serial monitor make sure no line-ending or if statements will not work
 * 
 * Android https://hpssjellis.github.io/web-serial-polyfill/index.html
 * Laptops Desktops  https://hpssjellis.github.io/my-examples-of-arduino-webUSB-webSerial/public/index.html
 * IOS     not really sure
 * 
 */



#include <Arduino.h> // Only needed for https://platformio.org/

String readString;

int myDelay = 5000;   // non-block delay in milliseconds
unsigned long myStart; 
int serialMessage = 1;
int myCount=48;      //48 = ascii 0,    58 ascii 9

void setup() {
  Serial.begin(9600);
  pinMode(LED_BUILTIN, OUTPUT);
  digitalWrite(LED_BUILTIN, HIGH);   // onboard LED, HIGH = off
  
  myStart = millis();   // set delay
  randomSeed(analogRead(A0));  // AO pin on XIAO does not have to be connected to anything

}

void loop() {

  if ( (millis() - myStart ) >= myDelay) {       
     myStart = millis();      //  reset the delay time
     myCount++;
     if (myCount >= 58){ // 48 = ascii 0,    58 ascii 9
       myCount = 48;
     }       
     //char myChar = (char)myCount;      
     byte myChar = (byte)myCount;    
     Serial.write(myChar);  
   }

  

  while (Serial.available()) {
    delay(3);  
    char c = Serial.read();
    readString += c; 
  }

  if (readString.length() > 0) {
    Serial.println(readString);

    if (readString == "a"){
      digitalWrite(LED_BUILTIN, LOW); //onboard LED LOW = on
      Serial.println("LED ON");
    }
    if (readString == "b"){
      digitalWrite(LED_BUILTIN, HIGH);
      Serial.println("LED OFF");
    }
    readString="";
  } 
}

  


```

Any suggestions or opinions are welcome?

This issue started as an issue on the arduino webusb library https://github.com/webusb/arduino/issues/96

**Comment by hpssjellis** [comment]
All done. Thanks. Awesome library!

[https://hpssjellis.github.io/web-serial-polyfill/desktop-serial05.html](https://hpssjellis.github.io/web-serial-polyfill/desktop-serial05.html)

**Comment by reillyeon** [comment]
We're talking about how to make it easier for developers to switch between the polyfill and native implementation (or use both at once!) in #10.

The source code for the terminal demo is here: https://github.com/GoogleChromeLabs/serial-terminal

It will switch to using the polyfill if you add the query parameter to the URL: https://googlechromelabs.github.io/serial-terminal/?polyfill.
