### ISSUE TITLE
Android: usb.getDevices() succeeds but serial.getDevices() fails

### ISSUE THREAD

**Issue by stewartoallen** [google/web-serial-polyfill#48]
Chrome on Android supports `navigator.usb` but not `navigator.serial` so I'm trying to use this polyfill to access a serial device that works from Chrome on Mac & PC.

The command that succeeds in finding and connecting to the device on all platforms, including Android:

```
navigator.usb.requestDevice({
    filters:[{
        vendorId: 0x0403,
        productId: 0x6001
    }]
}).then(p => console.log({p}))
```

I would expect the following to work, but it does not:

```
exports.serial.requestPort({
    filters:[{
        usbVendorId: 0x0403,
        usbProductId: 0x6001
    }]
}).then(p => console.log({p}))
```

the same command replacing `exports.serial` with `navigator.serial` on Mac and Windows succeeds. `getPorts()` similarly fails

**Comment by stewartoallen** [comment]
turns out the device shows up as class 0, not class 2. not sure what to do with this knowledge because I know nothing about usb-serial. but that's the filter that prevented it from showing. the `WebSerial` implementations do handle this somehow. 

<img width="272" alt="Screen Shot 2022-11-26 at 7 15 45 PM" src="https://user-images.githubusercontent.com/554275/204113743-7bc1191e-eb0c-4230-82a0-36da12663efc.png">

**Comment by reillyeon** [comment]
Device class 0 means "check the interface class" and interface class 255 means "vendor specific". This is an FTDI device which means it uses a vendor-specific USB serial protocol rather than the standard USB CDC-ACM protocol support by this polyfill. Issue #8 tracks adding support for FTDI chips.
