### ISSUE TITLE
Static web serial Polyfill NPM example please.

### ISSUE THREAD

**Issue by hpssjellis** [google/web-serial-polyfill#51]
@reillyeon  @scheib 

Can someone please post a static webpage demo that uses this polyfill npm from  https://www.npmjs.com/package/web-serial-polyfill?activeTab=readme

I can't test my code very well unless I can get a base webpage working.

**Comment by hpssjellis** [comment]
So I found this for the webSerial Terminal program


https://googlechromelabs.github.io/serial-terminal/?polyfill

but I get this error. It does ask for access to the device, but gives the error failed to execute "claimInterface"  I will look at the code and see what I can do with this.

![image](https://github.com/google/web-serial-polyfill/assets/5605614/f6e48de9-5601-44ec-a865-55274494f53c)

**Comment by reillyeon** [comment]
It looks like you're using Chrome on Android. You are probably on a device that ships with the USB CDC-ACM driver enabled and so the kernel has claimed the interface but since Android doesn't provide any API for applications to actually use that driver it's not helpful. You could confirm this by capturing an Android bug report and extracting the kernel log. Can you tell me what Android device model this is? I have heard from developers running into this problem but not encountered it myself.

[Chromium issue 1099521](https://bugs.chromium.org/p/chromium/issues/detail?id=1099521) tracks implementing an allowlist for interface classes where we will automatically try to take the interface away from any built-in drivers when a site requests that we claim the interface.

**Comment by hpssjellis** [comment]
Thanks for the reply @reillyeon I will look into getting the Android bug report. I use many Arduino's so I will see if any of the other ones work or if any other android phones work with them.  

My Phone is a  Samsung Galaxy S22 Ultra.

and I mainly work with the [Arduino PortentaH7](https://store-usa.arduino.cc/products/portenta-h7) or the new [Seeedstudio XIAO esp32S3
](https://wiki.seeedstudio.com/xiao_esp32s3_getting_started/)

**Comment by reillyeon** [comment]
You'll need to wait for a Chrome update. Please comment on the Chromium issue so we can keep track of how many developers are affected by this issue.

**Comment by hpssjellis** [comment]
Done @reillyeon thanks for making this polyfill code, the issues are out of your control. I will find a working phone and move on with the rest of my project. 

It would still be really useful to have a simply made, static webpage that does both webSerial and this polyfill using the npm you made. If you are interested I could submit a PR of a starting point with my page [here](https://hpssjellis.github.io/webMLserial/public/a06-android/accel03-webserial.html), I could strip out the extras for my project and just have a basic Arduino connection webpage with Arduino sketch.

**Comment by reillyeon** [comment]
I'm thinking about removing the demo page from this repo and directing developers to the serial terminal project instead, and making its use of the polyfill more obvious.

**Comment by hpssjellis** [comment]
> I'm thinking about removing the demo page from this repo and directing developers to the serial terminal project instead, and making its use of the polyfill more obvious.

@reillyeon The web serial terminal program at https://googlechromelabs.github.io/serial-terminal/?polyfill is a pain to have to change the url for desktop or Android. Is there any way it can be coded to auto switch to polyfill when ```navigator.serial``` is not detected, such as the code I use below?

```
document.getElementById('connectButton').addEventListener('click', () => {
  if (navigator.serial) {
    connectSerial();
  } else {
    document.getElementById('myDiv01').innerHTML = 'Web Serial API not supported. Switching to Polyfill<br>'
    myPoly();
  }
});
```
