### ISSUE TITLE
Feature request: Design a webpage that informs if webSerial or polyfill works on the device.

### ISSUE THREAD

**Issue by hpssjellis** [google/web-serial-polyfill#53]
@reillyeon 

Feature request: Design a webpage that informs if webSerial or polyfill works on the device and prints the results to the page instead of console.log

Background: I presently am testing my students Android cell phones to see which ones work with polyfill. I think my old Samsung S20? used to work but I had to trade it in to get my new phone. My very Old Samsung S8 does not work. The problem with testing is that I have to connect an Arduino to their phone to see if it works. It would be much easier to have the webApp determine if polyfill should work.

Presently I think most Google Pixel phones should work, but would like to know which other phones work and if any developer options can be used to make more phones work with Polyfill.

If someone can show me the code I will write the app.

I think @gohai is close with this p5.js testing program, just the code does not give any feedback about polyfill on the canvas.
https://github.com/gohai/p5.webserial/commit/f8993915235e91bc01a5b9a5d81dccd1147aa1ab

My testing is showing that you can't check if webSerial or usb polyfill can be used until you connect a device, so it looks like I am back to connecting Arduinos to student's phones.

Anyone have a list of Phones that work with polyfill or developer options to turn on the ability? Any suggestions?

**Comment by reillyeon** [comment]
Detecting whether the Web Serial API is supported is easy, just check if `navigator.serial` is defined. Unfortunately I don't think it's possible to detect whether the OS will block access to the device through WebUSB because of an existing driver until you try to actually connect to the device.
